Accessibility - Skip to main content link
Vets-Who-Code/vets-who-code-app pull request #355
Opened 2022-04-05 17:19 UTC by rmrose78

## Description
Added skip to main link/button shows when focused on first tab press. The link takes the user to id="our-story", with the greyscaled image and the #VetsWhoCode tag on the home page under the hero section. 

## Related Issue

## Motivation and Context
Change is required to increase site accessibility on the #VWC site to skip the navigation.

## How Has This Been Tested?
Checked to ensure that link/button is the first tab on multiple pages. 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2022-04-05 17:21 UTC, andrew-t-james approved these changes

2022-04-05 17:44 UTC, andrew-t-james requested changes

2022-04-05 17:44 UTC, andrew-t-james commented on src/assets/css/nav.css
> +#skip-to-main-link:hover {
I think we have styles that define an u decline already in the project. Could we reuse those instead of creating a new rule for the same effect?

2022-04-07 23:51 UTC, jeromehardaway approved these changes

2022-04-08 21:12 UTC, jeromehardaway approved these changes

2022-04-11 18:00 UTC, merged